"""
Django settings for crmcami project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from .authvars import DB_NAME, DB_USR, DB_PASS, DB_HOST, DB_PORT, SECRET_KEY, DEBUG, APPHOST


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = DEBUG
# HTTPS/cookies: seguras en prod, laxas en local (para poder loguear sobre http).
CSRF_COOKIE_SECURE = not DEBUG       # cookie CSRF solo por HTTPS en prod
SESSION_COOKIE_SECURE = not DEBUG    # cookie de sesion solo por HTTPS en prod
SECURE_SSL_REDIRECT = not DEBUG      # forzar HTTPS en prod

# Cloud Run termina el TLS y reenvia por HTTP interno; este header le dice a
# Django que la request original fue HTTPS (necesario para el redirect y las cookies secure).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# APPHOST = host de Cloud Run; se setea como env var recien cuando exista el servicio.
CSRF_TRUSTED_ORIGINS = []
if APPHOST:
    CSRF_TRUSTED_ORIGINS.append(f'https://{APPHOST}')

ALLOWED_HOSTS = ['localhost', '127.0.0.1']
if APPHOST:
    ALLOWED_HOSTS.append(APPHOST)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # apps propias
    'accounts',
]

# Usuario custom (AbstractUser vacio). DEBE quedar definido ANTES del primer
# migrate; cambiarlo despues es una migracion muy costosa.
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crmcami.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # templates propios (ej: login)
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crmcami.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# MySQL, mismo motor en local y prod. La diferencia local/prod es SOLO DB_HOST:
#   local: DB_HOST=127.0.0.1               -> conexion TCP
#   prod : DB_HOST=/cloudsql/PROJ:REG:INS  -> Django ve el "/" y usa socket unix (Cloud SQL)
# Secretos montados como env vars (Google Secret Manager) en Cloud Run.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DB_NAME,
        'USER': DB_USR,
        'PASSWORD': DB_PASS,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
        'CONN_MAX_AGE': 0,   # Cloud Run serverless: conexion nueva por request
                             # (evita agotar el max_connections de Cloud SQL).
        'OPTIONS': {
            'sql_mode': 'STRICT_TRANS_TABLES',
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, 'appinfo/templates/static'),
    os.path.join(BASE_DIR, 'static'),   # estaticos propios (logo, bundles JS...); static != templates
    # os.path.join(BASE_DIR, r'media'),    
]