# Generated by Django 6.0.7 on 2026-07-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watermark', models.BigIntegerField(default=0)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_ok', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_importados', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estado de sincronizacion WP',
                'verbose_name_plural': 'Estado de sincronizacion WP',
            },
        ),
    ]
