# Generated by Django 6.0.7 on 2026-07-28 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('cliente', models.CharField(max_length=255)),
                ('servicio', models.CharField(blank=True, choices=[('Almacenamiento', 'Almacenamiento'), ('Cross-docking', 'Cross-docking')], max_length=40)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('origen', models.CharField(blank=True, choices=[('Google Ads', 'Google Ads'), ('Meta Ads', 'Meta Ads'), ('Redes sociales', 'Redes sociales'), ('Referido', 'Referido'), ('Sitio web', 'Sitio web'), ('SIGNOS', 'SIGNOS')], max_length=40)),
                ('sub_origen', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('1. Datos pendientes', '1. Datos pendientes'), ('2. Pendiente cotizar', '2. Pendiente cotizar'), ('3. Cotizado', '3. Cotizado'), ('4. Interesado', '4. Interesado'), ('5. Negociando / Re-cotizar', '5. Negociando / Re-cotizar'), ('6. Venta ganada', '6. Venta ganada'), ('7. No viable', '7. No viable'), ('8. No avanzó', '8. No avanzó')], default='1. Datos pendientes', max_length=40)),
                ('sub_estado', models.CharField(blank=True, choices=[('Sin respuesta', 'Sin respuesta'), ('Eligió competencia', 'Eligió competencia'), ('Cotización fuera de presupuesto', 'Cotización fuera de presupuesto'), ('Proyecto pospuesto', 'Proyecto pospuesto'), ('Tardanza comercial', 'Tardanza comercial'), ('Otro', 'Otro'), ('SENASA', 'SENASA'), ('ANMAT', 'ANMAT'), ('RENPRE', 'RENPRE'), ('Transporte', 'Transporte'), ('Fuera de alcance geográfico', 'Fuera de alcance geográfico')], max_length=60)),
                ('estado_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha del ultimo cambio de estado')),
                ('wp_entry_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(verbose_name='Fecha y hora')),
                ('texto', models.TextField()),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='crm.lead')),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='TallyNoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(choices=[('Empleo / RRHH', 'Empleo / RRHH'), ('Proveedores', 'Proveedores'), ('Otro / Spam', 'Otro / Spam')], max_length=40)),
                ('cantidad', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('fecha', 'categoria'), name='uniq_tally_fecha_categoria')],
            },
        ),
    ]
